version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mottu-postgres
    environment:
      POSTGRES_DB: mottu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mottu-network

  app:
    build: .
    container_name: mottu-api
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mottu
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - mottu-network

volumes:
  postgres_data:

networks:
  mottu-network:
    driver: bridge
