# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Log para investigar erro 500 no Swagger
logging.level.org.springdoc=DEBUG
logging.level.org.springframework=INFO

server.port=8081

